version: '3'

services:
  grafana:
    # Use multi-stage build in prod to automatically build the plugins
    build: .
    container_name: grafana
    environment:
      - GRAFANA_CLIENT_ID=$GRAFANA_CLIENT_ID
      - GRAFANA_CLIENT_SECRET=$GRAFANA_CLIENT_SECRET
      - GRAFANA_SCOPE=$GRAFANA_SCOPE

    ports:
      - 3000:3000
    volumes:
 #     - ./grafana-datasource/dist:/var/lib/grafana/plugins/dcd-datasource
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
      - $HOST_DATA_FOLDER/grafana/data:/db
      - $HOST_DATA_FOLDER/grafana/logs:/var/log/grafana

networks: 
  default:
      external:
        name: dcd-net