version: '3'

services:
  grafana:
    # image: grafana/grafana:7.1.1
    build:
      context: ./grafana-datasource
    container_name: grafana
    environment:
      - GF_SERVER_PROTOCOL=$GRAFANA_PROTOCOL
#      - GF_SERVER_CERT_FILE=<path>\cert.pem
#      - GF_SERVER_CERT_KEY=<path>\server.key
      - GF_SERVER_DOMAIN=$GRAFANA_DOMAIN
      - GF_SERVER_ROOT_URL=$GRAFANA_ROOT_URL

      - GF_AUTH_GENERIC_OAUTH_ENABLED=true
      - GF_AUTH_GENERIC_OAUTH_CLIENT_ID=$GRAFANA_CLIENT_ID
      - GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=$GRAFANA_CLIENT_SECRET
      - GF_AUTH_GENERIC_OAUTH_SCOPES=$GRAFANA_SCOPE
      - GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://dwd.tudelft.nl:443/oauth2/auth
      - GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://dwd.tudelft.nl:443/oauth2/token
      - GF_AUTH_GENERIC_OAUTH_API_URL=https://dwd.tudelft.nl:443/userinfo
      - GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP=true
      - GF_AUTH_GENERIC_OAUTH_SEND_CLIENT_CREDENTIALS_VIA_POST=true

    # ports:
    #   - 3000:3000
    # volumes:
    #   - .:/var/lib/grafana/plugins

networks: 
  default:
      external:
        name: dcd-net