version: '3'

services:
  grafana:
    # Use multi-stage build in prod to automatically build the plugins
    build: .
    container_name: grafana
    environment:
      - GRAFANA_CLIENT_ID=$GRAFANA_CLIENT_ID
      - GRAFANA_CLIENT_SECRET=$GRAFANA_CLIENT_SECRET
      - GRAFANA_SCOPE=$GRAFANA_SCOPE
      - GRAFANA_PROTOCOL=$GRAFANA_PROTOCOL
      - GRAFANA_DOMAIN=$GRAFANA_PROTOCOL
      - GRAFANA_ROOT_URL=$GRAFANA_ROOT_URL
      - GRAFANA_ADMIN_USER=$GRAFANA_ADMIN_USER
      - GRAFANA_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
      
    ports:
      - 3000:3000
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
      - ./provisioning:/etc/grafana/provisioning
      - $HOST_DATA_FOLDER/grafana/data:/db
      - $HOST_DATA_FOLDER/grafana/logs:/var/log/grafana

networks: 
  default:
      external:
        name: dcd-net